application: project-sparkles
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts/glyphicons
  static_dir: fonts/glyphicons

- url: /fonts/lato
  static_dir: fonts/lato

- url: /
  script: sparklesPython.index.app

- url: /index\..*
  script: sparklesPython.index.app

- url: /run/auto\..*
  script: sparklesPython.runAuto.app

- url: /run/manual\..*
  script: sparklesPython.runManual.app

- url: /run/.*
  script: sparklesPython.runManual.app

- url: /settings/locations\..*
  script: sparklesPython.locations.app

- url: /settings/profiles\..*
  script: sparklesPython.profiles.app

- url: /settings/general\..*
  script: sparklesPython.general.app

- url: /settings/.*
  script: sparklesPython.general.app

- url: .*
  script: sparklesPython.notFound.app
